server:
  port: 8085

hm:
  db:
    database: hm-trade
  swagger:
    title: "黑马商城交易接口文档"
    package: com.hmall.trade.controller
feign:
  okhttp:
    enabled: true

# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123